<?php
/** @var $this Ml_Testimonials_Block_Edit  */

/** @var Mage_Customer_Model_Customer $_customer */
$_customer = $this->_getCurrentCustomer();
?>

<div class="page-title">
    <h2><?php echo $this->__('Edit Testimonial') ?></h2>
</div>

<form id="person-form-validate" method="post" action="<?php echo $this->_getFormAction()?>">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Testimonial')?></h2>
        <ul class="form-list">
            <li class="fields">
                <div class="testimonial-data">
                    <div class="field name-firstname">
                        <label class="required" for="firstname"><em>*</em><?php echo $this->__('Name')?></label>
                        <div class="input-box">
                            <input type="text"
                                   class="input-text required-entry"
                                   maxlength="255"
                                   title="Name"
                                   value="<?php echo $_customer->getName() ? $_customer->getName() : '' ?>"
                                   name="name"
                                   id="name">
                        </div>
                    </div>
                    <div class="field email">
                        <label class="required-entry validate-email" for="email"><em>*</em><?php echo $this->__('Email')?></label>
                        <div class="input-box">
                            <input type="text"
                                   class="input-text required-entry"
                                   maxlength="255"
                                   title="Email"
                                   value="<?php echo $_customer->getEmail() ? $_customer->getEmail() : ''  ?>"
                                   name="email"
                                   id="email">
                        </div>
                    </div>
                    <div class="field testimonial">
                        <label class="required" for="description"><em>*</em><?php echo $this->__('Testimonial')?></label>
                        <div class="input-box">
                            <textarea id="description" name="description" cols="2" rows="6"></textarea>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required">* <?php echo $this->__('Required Fields')?></p>
        <p class="back-link"><a class="back-link" href="<?php echo $this->getBaseUrl();?>"><small>&laquo;</small>Back</a></p>
        <button class="button" title="Submit" type="submit"><span><span><?php echo $this->__('Submit')?></span></span></button>
    </div>
</form>